config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bottles do
    collection do
      get "/:filter", to: "bottles#index", as: :filtered, constraints: { filter: /open|finished|sell|stocked|unstocked/ }
      get "/search", to: "bottles#search", as: :search
      get "/toggle_inventory", to: "bottles#toggle_inventory", as: :toggle_inventory
      get "/reset_stock", to: "bottles#reset_stock", as: :reset_stock
    end

    member do
      get "/duplicate", to: "bottles#duplicate", as: :duplicate
      get "/stock", to: "bottles#stock", as: :stock
      get "/unstock", to: "bottles#unstock", as: :unstock
      get "/open", to: "bottles#crack_open", as: :open
      get "/finish", to: "bottles#finish", as: :finish
      get "/sell", to: "bottles#sell", as: :sell
    end
  end

  root to: "bottles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle.rb
require 'csv'

class Bottle < ApplicationRecord
  include PgSearch::Model

  acts_as_taggable

  attr_accessor :abv, :quantity

  belongs_to :user
  validates :user, presence: true

  validates :name, presence: true
  validates :spirit, presence: true
  validates :location, presence: true, unless: -> (bottle) { bottle.finished? }
  validates :acquired_on, presence: true

  validates :volume, presence: true
  validates :volume, numericality: { greater_than: 0, only_integer: true }

  validates :quantity, numericality: { greater_than: 0, only_integer: true }

  validates :proof, numericality: { greater_than: 0 }, allow_blank: true
  validates :abv, numericality: { greater_than: 0 }, allow_blank: true

  validates :release_year, numericality: { greater_than: 0, only_integer: true, allow_blank: true }

  scope :open, -> { where(open: true) }
  scope :unopened, -> { where(open: false) }
  scope :finished, -> { where.not(finished_on: nil) }
  scope :current, -> { where(finished_on: nil) }
  scope :stocked, -> { where(in_stock: true) }
  scope :unstocked, -> { where(in_stock: false) }

  pg_search_scope :search_for,
    against: %i(name details producer spirit release_year notes location),
    using: {
      tsearch: { prefix: true }
    }

  def finished?
    finished_on.present?
  end

  def quantity
    @quantity || 1
  end

  def abv=(new_abv)
    @abv = new_abv
    self[:proof] = @abv.to_i * 2 if proof.nil?
  end

  def location=(new_location)
    self[:location] = new_location.try(:titleize)
  end

  def spirit=(new_spirit)
    self[:spirit] = new_spirit.try(:titleize)
  end

  def self.to_csv
    attributes = %w(
      name
      details
      spirit
      release_year
      producer
      volume
      proof
      price
      location
      open
      in_stock
      source
      acquired_on
      finished_on
      tag_list
      notes
      created_at
      updated_at
    )

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |bottle|
        csv << attributes.map { |attr| bottle.send(attr) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable,
         :validatable

  has_many :bottles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bottle, only: [:show, :edit, :update, :destroy, :stock, :unstock, :crack_open, :finish, :sell]

  # GET /bottles
  # GET /bottles.json
  def index
    @bottles = Bottle.where(user: current_user).order(Arel.sql('LOWER(name), release_year'))
    @filter = params[:filter].try(:downcase)

    case @filter
    when "open"
      @bottles = @bottles.current.open
    when "finished"
      @bottles = @bottles.finished
    when "sell"
      @bottles = @bottles.current.tagged_with("sell")
    when "stocked"
      @bottles = @bottles.current.stocked
    when "unstocked"
      @bottles = @bottles.current.unstocked
    else
      @bottles = @bottles.current
    end

    respond_to do |format|
      format.html
      format.csv { send_data @bottles.to_csv, filename: "bottles-#{Date.today.strftime('%Y-%m-%d')}.csv" }
    end
  end

  def search
    @bottles = Bottle.where(user: current_user).order('LOWER(name), release_year')

    @query = params[:q]
    @bottles = @bottles.search_for(@query)

    @open_bottles = @bottles.current.open
    @unopened_bottles = @bottles.current.unopened
    @finished_bottles = @bottles.finished

    respond_to do |format|
      format.html
      format.csv { send_data @bottles.to_csv, filename: "bottles-#{@query.parameterize}-#{Date.today.strftime('%Y-%m-%d')}.csv" }
    end
  end

  # GET /bottles/1
  # GET /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
  end

  def duplicate
    @bottle = Bottle.find(params[:id]).dup
  end

  # GET /bottles/1/edit
  def edit
  end

  # POST /bottles
  # POST /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)
    @bottle.user = current_user

    if @bottle.quantity == 1
      saved_successfully = @bottle.save
    else
      # Try and create #{quantity} records
      saved_successfully = false

      if @bottle.valid?
        Bottle.transaction do
          @bottle.quantity.to_i.times do
            new_bottle = @bottle.dup
            new_bottle.save!
          end

          saved_successfully = true
        end
      end
    end

    respond_to do |format|
      if saved_successfully
        format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
        format.json { render :show, status: :created, location: @bottle }
      else
        format.html { render :new }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1
  # PATCH/PUT /bottles/1.json
  def update
    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bottle }
      else
        format.html { render :edit }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url, notice: 'Bottle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_inventory
    current_user.toggle(:taking_inventory).save
    redirect_to bottles_path
  end

  def reset_stock
    Bottle.update_all(in_stock: false)
    redirect_to bottles_path
  end

  def stock
    @bottle.update(in_stock: true)
  end

  def unstock
    @bottle.update(in_stock: false)
  end

  def crack_open
    @bottle.update(open: true)
    redirect_to @bottle
  end

  def finish
    @bottle.update(finished_on: Date.today)
    redirect_to @bottle
  end

  def sell
    if @bottle.tag_list.include?("sell")
      @bottle.tag_list.remove("sell")
    else
      @bottle.tag_list.add("sell")
    end

    @bottle.save
    redirect_to @bottle
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find_by(user: current_user, id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bottle_params
      params.require(:bottle).permit(
        :name,
        :details,
        :producer,
        :spirit,
        :volume,
        :proof,
        :abv,
        :release_year,
        :price,
        :source,
        :acquired_on,
        :notes,
        :open,
        :finished_on,
        :location,
        :quantity,
        :in_stock
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: 'alert-success',
      notice: 'alert-info',
      alert: 'alert-warning',
      error: 'alert-danger'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def page_heading(title, button_text = nil, button_url = nil)
    content_for(:title, title)

    content_tag(:div, class: "page-header") do
      if button_text.present? && button_url.present?
        concat link_to(button_text, button_url, class: "btn btn-primary float-xs-right")
      end

      concat content_tag(:h1, title)
    end
  end
end

app/views/bottles/_bottle_list.html.erb
<ul class="list-unstyled bottles-list">
  <% bottles.each do |bottle| %>
    <li class="row bottle-list-item">
      <div class="<%= current_user.taking_inventory? ? "col-xs-10" : "col-xs-12" %>">
        <div class="row">
          <div class="col-md-7">
            <%= link_to bottle.name, bottle_path(bottle), class: "bottle-name" %>
            <% if bottle.details.present? %>
              <br>
              <small class="text-muted"><%= bottle.details %></small>
            <% end %>
          </div>
          <div class="col-md-5 bottle-details">
            <div class="row">
              <div class="col-xs-2">
                <%= bottle.release_year %>
              </div>
              <div class="col-xs-3">
                <%= bottle.spirit %>
              </div>
              <div class="col-xs-2">
                <%= bottle.proof %>&deg;
              </div>
              <div class="col-xs-2">
                <%= bottle.volume %>ml
              </div>
              <div class="col-xs-2">
                <%= bottle.location %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <% if current_user.taking_inventory? %>
        <div class="col-xs-2">
          <%= render "stock_button", bottle: bottle, append_class: "btn-sm pull-right" %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/bottles/_form.html.erb
<%= bootstrap_form_for(bottle, label_errors: true) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :details, help: "Private selection, bottle nickname, etc." %>
  <%= f.text_field :producer %>
  <%= f.select :spirit, %w(Bourbon Rye Scotch Rum Gin Other) %>
  <%= f.number_field :volume %>

  <div class="row">
    <div class="col-md-6">
      <%= f.number_field :proof, step: "any" %>
    </div>
    <div class="col-md-6">
      <%= f.number_field :abv, label: "ABV", step: "any" %>
    </div>
  </div>

  <%= f.select :release_year, (1870..Time.now.year).to_a.reverse %>

  <%= f.number_field :price, step: "0.01" %>
  <%= f.text_field :source %>
  <%= f.text_field :acquired_on, value: f.object.acquired_on || Date.today, class: "datepicker" %>
  <%= f.text_field :location %>
  <%= f.text_area :notes %>

  <% unless bottle.persisted? %>
    <%= f.number_field :quantity %>
  <% end %>

  <%= f.check_box :in_stock%>
  <%= f.check_box :open %>

  <%= f.text_field :finished_on, class: "datepicker" %>

  <%= f.primary %>
<% end %>

app/views/bottles/_searchbar.html.erb
<div class="row">
  <div class="col-md-6">
    <%= bootstrap_form_tag(url: search_bottles_url, method: :get) do |f| %>
      <%= f.text_field :q, hide_label: true, value: @query, append: f.submit("Search", class: "btn btn-primary") %>
      <p class="text-muted">
        <% if defined?(@bottles) %>
          <%= pluralize(@bottles.size, "bottle") %> found
        <% end %>
        <% if @query.present? %>| <%= link_to "Clear search", bottles_path %><% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/bottles/_stock_button.html.erb
<%= link_to (bottle.in_stock? ? unstock_bottle_path(bottle) : stock_bottle_path(bottle)),
  remote: true,
  data: { "bottle-id" => bottle.id },
  class: "stock-toggle btn btn-#{bottle.in_stock? ? "success" : "default"} " + append_class do
%>
  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
<% end %>

app/views/bottles/duplicate.html.erb
<%= page_heading("Duplicate Bottle") %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form', bottle: @bottle %>
  </div>
</div>

app/views/bottles/edit.html.erb
<%= page_heading("Edit Bottle") %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form', bottle: @bottle %>
  </div>
</div>

app/views/bottles/index.html.erb
<% page_title = "#{@filter.present? ? @filter.capitalize : "Current" } Bottles" %>

<div class="page-header">
  <h1><%= page_title %></h1>
</div>

<%= render "searchbar" %>

<%= render "bottle_list", bottles: @bottles %>

<div style="margin: 40px 0;">
  <%= link_to 'Download CSV', format: :csv %>
</div>

app/views/bottles/new.html.erb
<%= page_heading("Add Bottle") %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form', bottle: @bottle %>
  </div>
</div>

app/views/bottles/search.html.erb
<% page_title = "Search Results" %>

<div class="page-header">
  <%= link_to "Add Bottle", new_bottle_path, class: "btn btn-success pull-right hidden-xs" %>
  <%= link_to new_bottle_path, class: "btn btn-success pull-right visible-xs" do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
  <% end %>
  <h1><%= page_title %></h1>
</div>

<%= render "searchbar" %>

<% if @open_bottles.any? %>
  <h2>Open Bottles <small>(<%= @open_bottles.size %>)</small></h2>
  <%= render "bottle_list", bottles: @open_bottles %>
<% end %>

<% if @unopened_bottles.any? %>
  <h2>Unopened Bottles <small>(<%= @unopened_bottles.size %>)</small></h2>
  <%= render "bottle_list", bottles: @unopened_bottles %>
<% end %>

<% if @finished_bottles.any? %>
  <h2>Finished Bottles <small>(<%= @finished_bottles.size %>)</small></h2>
  <%= render "bottle_list", bottles: @finished_bottles %>
<% end %>

<div style="margin: 40px 0;">
  <%= link_to 'Download CSV', format: :csv, q: @query %>
</div>

app/views/bottles/show.html.erb
<%= content_for(:title, @bottle.name) %>

<div class="page-header">
  <h1><%= @bottle.name %></h1>
  <% if @bottle.details.present? %>
    <h3 class="text-muted"><%= @bottle.details %></h3>
  <% end %>
</div>

<div class="mb-medium clearfix">
  <div class="pull-left">
    <% if @bottle.finished? %>
      <span class="bottle-status-finished">
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Finished
      </span>
    <% elsif @bottle.open? %>
      <span class="bottle-status-open">
        <span class="glyphicon glyphicon-grain" aria-hidden="true"></span> Open
      </span>
      <%= link_to "Finish", finish_bottle_path(@bottle), class: "btn btn-info" %>
    <% else %>
      <%= link_to "Open", open_bottle_path(@bottle), class: "btn btn-info" %>
    <% end %>

    <% if @bottle.tag_list.include?("sell") %>
      <%= link_to "Don't Sell", sell_bottle_path(@bottle), class: "btn btn-warning" %>
    <% else %>
      <%= link_to "Sell", sell_bottle_path(@bottle), class: "btn btn-info" %>
    <% end %>
  </div>

  <div class="pull-right mb-medium">
    <%= link_to "Edit", edit_bottle_path(@bottle), class: "btn btn-primary" %>
    <%= link_to "Duplicate", duplicate_bottle_path(@bottle), class: "btn btn-default" %>
    <% if current_user.taking_inventory? %>
      <%= render "stock_button", bottle: @bottle, append_class: "" %>
    <% end %>
  </div>
</div>

<div class="row bottle-data">
  <div class="col-sm-6">
    <table class="table">
      <tr>
        <td><strong>Spirit</strong></td>
        <td><%= @bottle.spirit%></td>
      </tr>
      <tr>
        <td><strong>Producer</strong></td>
        <td><%= @bottle.producer %></td>
      </tr>
      <tr>
        <td><strong>Release Year</strong></td>
        <td><%= @bottle.release_year %></td>
      </tr>
      <tr>
        <td><strong>Proof</strong></td>
        <td><%= @bottle.proof %></td>
      </tr>
      <tr>
        <td><strong>Volume</strong></td>
        <td><%= @bottle.volume %></td>
      </tr>
      <tr>
        <td><strong>Price</strong></td>
        <td><%= @bottle.price %></td>
      </tr>
    </table>
  </div>

  <div class="col-sm-6">
    <table class="table">
      <tr>
        <td><strong>Bottle Location</strong></td>
        <td><%= @bottle.location %></td>
      </tr>
      <tr>
        <td><strong>Source</strong></td>
        <td><%= @bottle.source%></td>
      </tr>
      <tr>
        <td><strong>Acquired On</strong></td>
        <td><%= @bottle.acquired_on %></td>
      </tr>
      <tr>
        <td><strong>Open</strong></td>
        <td><%= @bottle.open? ? "Yes" : "No" %></td>
      </tr>
      <tr>
        <td><strong>Finished On</strong></td>
        <td><%= @bottle.finished_on %></td>
      </tr>
      <tr>
        <td><strong>In Stock</strong></td>
        <td><%= @bottle.in_stock? ? "Yes" : "No" %></td>
      </tr>
    </table>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Notes</div>
  <div class="panel-body">
    <%= @bottle.notes %>
  </div>
</div>

<%= link_to "Delete", bottle_path(@bottle), method: :delete, class: "text-danger", data: { confirm: "Are you sure you want to delete this bottle?" } %>

app/views/bottles/stock.js.erb
$('.stock-toggle[data-bottle-id="<%= @bottle.id %>"]')
  .attr('href', '<%= unstock_bottle_path(@bottle) %>')
  .removeClass('btn-default')
  .addClass('btn-success');

app/views/bottles/unstock.js.erb
$('.stock-toggle[data-bottle-id="<%= @bottle.id %>"]')
  .attr('href', '<%= stock_bottle_path(@bottle) %>')
  .removeClass('btn-success')
  .addClass('btn-default');

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Whiskey Bar", root_path, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <%= link_to "Add Bottle", new_bottle_path, class: "nav-link" %>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filter <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <%= link_to "Current", bottles_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Open", filtered_bottles_path(filter: :open), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "To Sell", filtered_bottles_path(filter: :sell), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Finished", filtered_bottles_path(filter: :finished), class: "nav-link" %>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inventory <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="nav-item">
                <%= link_to "Stocked", filtered_bottles_path(filter: :stocked), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Not Stocked", filtered_bottles_path(filter: :unstocked), class: "nav-link" %>
              </li>
              <li role="separator" class="divider"></li>
              <li class="nav-item">
                <% if current_user.taking_inventory? %>
                  <%= link_to "End Inventory", toggle_inventory_bottles_path, data: { confirm: "End Inventory?" } %>
                <% else %>
                  <%= link_to "Start Inventory", toggle_inventory_bottles_path, data: { confirm: "Start Inventory?" } %>
                <% end %>
              </li>
              <li role="separator" class="divider"></li>
              <li class="nav-item">
                <%= link_to "Reset Stock", reset_stock_bottles_path, data: { confirm: "Reset all stock?" } %>
              </li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <%= link_to "Sign up", new_registration_path(resource_name), class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Whiskey Bar is a home whiskey inventory tracking tool for collectors.">
    <meta name="author" content="Tim Cheadle">

    <title>Whiskey Bar<%= content_for?(:title) ? " | " + yield(:title) : "" %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-dismissable <%= bootstrap_class_for(type) %>">
          <button class="close" data-dismiss="alert">&times;</button>
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>